MACOSX_SDK_VERSION:     # [osx]
  - "26.0"  # [osx]
  - "15.5"  # [osx]
  - "15.4"  # [osx]
  - "15.2"  # [osx]
  - "15.1"  # [osx]
  - "15.0"  # [osx]
  - "14.5"  # [osx]
  - "14.4"  # [osx]
  - "14.2"  # [osx]
  - "14.0"  # [osx]
  - "13.3"  # [osx]
  - "13.1"  # [osx]
  - "13.0"  # [osx]
  - "12.3"  # [osx]
  - "12.1"  # [osx]
  - "12.0"  # [osx]